# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Agile Coaching in the Philippines"
description: > # this means to ignore newlines until "email:"
  Thoughts and ideas of Mike Mallete - Agile Coach, Trainer, and Software Developer

email: mike@odd-e.com
#blog logo
logo: "/assets/images/m_logo.jpg"
# blog cover
cover: "/assets/images/bg.jpg"
closer: "/assets/images/footer.jpg"

name: 'Mike Mallete'
author: 'Mike Mallete'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://agilecoach.ph"
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/mike_mallete
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/mikemallete
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
